
// get all customers
GET http://localhost:3000/customers HTTP/1.1

###

// create customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":17, 
"firstName": "Jiali",    
"lastName": "Johnson",
"userName": "John2",
"email": "123@gmail.com",
"password": "123"
}

###
// check login
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{"username": "John2", "password": "1234"}
###

// get customer by id
# GET http://localhost:3000/customers/15 HTTP/1.1

# ###

# // update customer
# PUT  http://localhost:3000/customers/15 HTTP/1.1
# content-type: application/json

# {"customerId":15, "customerName": "John Johnson UPDATED!"}
# ###

# // delete customer
# DELETE  http://localhost:3000/customers/17 HTTP/1.1

###